
spring:
  application:
    name: mdService # 项目名称
  datasource: # mysql配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    # &allowMultiQueries=true 允许批量执行sql语句
    url: jdbc:mysql://localhost:3307/md_service?&allowMultiQueries=true
    username: root
    #password: yourpassword
    password: root
  servlet: # 上传文件大小配置
    multipart:
      max-request-size: 10MB
      max-file-size: 100MB
  data:
    redis: # redis配置
      database: 0
      host: localhost
      port: 6379 # redis端口
      # password: yourpassword #有密码设置密码

langchain4j:
  open-ai:
    chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: sk-2e45978d0b81417fbb2708ff78d9adb7
      model-name: deepseek-v3
      temperature: 0.0

mybatis: # mybatis配置
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名
  mapper-locations: classpath:mapper/**/*.xml # mybatis的映射sql文件目录

jwt:
  secret: "MySuperSecretKeyThatIsAtLeast32BytesLongForSecurity"
  expiration: 864000000

file: # 自定义文件上传配置
  upload:
    dev-path: src/main/resources/upload # 开发环境
    prod-path: /opt/upload # 生产环境
    access-prefix: /upload/ # 访问前缀（用于前端访问）


server:
  port: 8080 # 项目启动端口

logging: # 日志配置
  level: # 日志级别
    com.mdservice: debug
  pattern: # 输出格式
    dateformat: HH:mm:ss:SSS
  file: # 输出路径
    path: "logs/${spring.application.name}"